version: 3

tasks:
  cache:
    cmd: go mod tidy

  htmx:
    cmds:
      - curl -L -o static/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js
      - curl -L -o static/hyperscript.min.js https://unpkg.com/hyperscript.org@latest/dist/_hyperscript.min.js

  dev:
    deps:
      - cache
    cmds:
    # TODO -- env override
      - infisical run --env=dev --path=ember-allspice -- go run ./cmd/ember-allspice/

  env:
    cmds:
      - infisical secrets --env=dev --path=ember-allspice {{.CLI_ARGS}}

  img:
    cmds: 
      - docker build -t ember-allspice .
      - docker run --rm -d -p 8000:8000 ember-allspice